### ISSUE TITLE
Add Lab 7

### ISSUE THREAD

**Issue by aashutoshrathi** [anshumanv/LAB-Signals-Systems#7]
- [x] Assign Baba to this issue

**Comment by starkblaze01** [comment]
Issue fixed
But note that in Question one I have used 'fft' the function directly. You can also do it without using Fourier Transform by using the for loop and applying Summation. And also note that in Q4 part b we can do without using fft function as Constant function is not absolutely Summable. So, can do in code without using fft function So, not uploaded it.

**Comment by anshumanv** [comment]
Arey baba :raised_hands:
